openapi: 3.0.0
info:
  title: SpringTaskTodoApp
  version: 1.0.0
paths:
  /tasks:
    get:
      tags:
        - tasks
      summary: Get all tasks.
      description: Returns an array of task model
      parameters: []
      responses:
        "200":
          description: A JSON array of task model
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
                example:
                  - _id: "603a30927735b35403eb2bb9"
                    name: "Test"
                    Created_date: "2021-02-27T11:44:18.014Z"
                    __v: 0
    post:
      tags:
        - tasks
      summary: Create a new task
      description: Create a new task
      parameters: []
      requestBody:
        description: task to create
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
            example:
              - _id: "503a30927735b35403ea2bb9"
                name: "Post Test"
                Created_date: "2021-02-27T11:54:18.014Z"
                __v: 1
      responses:
        "201":
          description: CREATED
  /tasks/{taskId}:
    get:
      tags:
        - tasks
      summary: Get task by ID.
      description: Returns a single task model
      parameters:
        - name: taskId
          in: path
          description: task id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A single task model
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Task"
                example:
                  - _id: "603a30927735b35403eb2bb9"
                    name: "Test"
                    Created_date: "2021-02-27T11:44:18.014Z"
                    __v: 0
    put:
      tags:
        - tasks
      summary: Update task by ID
      description: Updates a single task model
      parameters:
        - name: taskId
          in: path
          description: task id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Updates a single task model
          content:
            application/json:
              schema: object
              items:
                  $ref: "#/components/schemas/Task"
                example:
                  - _id: "603a30927735b35403eb2bb9"
                    name: "Update Test"
                    Created_date: "2021-02-27T11:44:18.014Z"
                    __v: 0
    delete:
      tags:
        - tasks
      summary: Delete task by ID
      description: Deletes a single task model
      parameters:
        - name: taskId
          in: path
          description: task id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Deletes a single task model
          content:
            application/json:
              schema: object
              items:
                  $ref: "#/components/schemas/Task"
                example:
                  - _id: "603a30927735b35403eb2bb9"
                    name: "Update Test"
                    Created_date: "2021-02-27T11:44:18.014Z"
                    __v: 0
components:
  schemas:
    Task:
      type: object
      required:
        - name
      properties:
        _id:
          type: string
        name:
          type: string
        Created_date:
          type: string
        __v:
          type: integer
          format: int32
